__include__: [
  '../dataset/coco_detection.yml',
  '../runtime_distillation.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './student/rtdetrv2_r50vd.yml',
  './teacher/relation_detr_focalnet_large_lrf_fl4_1200_2000.yml',
]


output_dir: ./output/relation_detr_focalnet_distill_to_rtdetr_r50vd


optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001


criterion: RTDETRCriterionv2Distill

RTDETRCriterionv2Distill:
  weight_dict: {loss_vfl: 1, loss_bbox: 5, loss_giou: 2, distill_cls_loss: 1, distill_bbox_loss: 5, distill_giou_loss: 2, }
  # losses: ['vfl', 'boxes', 'distillation']
  losses: ['distillation', ] # distillation only
  alpha: 0.75
  gamma: 2.0
  num_layers: 6

  matcher:
    type: HungarianMatcher
    weight_dict: {cost_class: 2, cost_bbox: 5, cost_giou: 2}
    alpha: 0.25
    gamma: 2.0

  distiller:
    type: KD
    temperature: 0.5

  teacher_resetter:
    type: BlankResetter
